export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
export const CLEAR_THE_CART = "CLEAR_THE_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
