export const SET_ORDER_CREATE_LOADING = "SET_ORDER_CREATE_LOADING";
export const SET_ORDER_CREATE_SUCCESS = "SET_ORDER_CREATE_SUCCESS";
export const SET_ORDER_CREATE_ERROR = "SET_ORDER_CREATE_ERROR";

export const SET_ORDER_CREATE_RESET = "SET_ORDER_CREATE_RESET";
