export const SET_ORDER_CREATE_LOADING = "SET_ORDER_CREATE_LOADING";
export const SET_ORDER_CREATE_SUCCESS = "SET_ORDER_CREATE_SUCCESS";
export const SET_ORDER_CREATE_ERROR = "SET_ORDER_CREATE_ERROR";

export const SET_ORDER_LIST_LOADING = "SET_ORDER_LIST_LOADING";
export const SET_ORDER_LIST_SUCCESS = "SET_ORDER_LIST_SUCCESS";
export const SET_ORDER_LIST_ERROR = "SET_ORDER_LIST_ERROR";

export const SET_ORDER_RESET = "SET_ORDER_CREATE_RESET";

export const SET_ORDER_DETAIL_LOADING = "SET_ORDER_DETAIL_LOADING";
export const SET_ORDER_DETAIL_SUCCESS = "SET_ORDER_DETAIL_SUCCESS";
export const SET_ORDER_DETAIL_ERROR = "SET_ORDER_DETAIL_ERROR";

export const SET_ORDER_PAY_LOADING = "SET_ORDER_PAY_LOADING";
export const SET_ORDER_PAY_SUCCESS = "SET_ORDER_PAY_SUCCESS";
export const SET_ORDER_PAY_ERROR = "SET_ORDER_PAY_ERROR";
