export const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING";
export const SET_PRODUCTS_SUCCESS = "SET_PRODUCTS_SUCCESS";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

export const SET_PRODUCT_DETAIL_LOADING = "SET_PRODUCT_DETAIL_LOADING";
export const SET_PRODUCT_DETAIL_SUCCESS = "SET_PRODUCT_DETAIL_SUCCESS";
export const SET_PRODUCT_DETAIL_ERROR = "SET_PRODUCT_DETAIL_ERROR";
