export const SET_USER_LOGIN_LOADING = "SET_USER_LOGIN_LOADING";
export const SET_USER_LOGIN_SUCCESS = "SET_USER_LOGIN_SUCCESS";
export const SET_USER_LOGIN_ERROR = "SET_USER_LOGIN_ERROR";

export const SET_USER_LOGOUT = "SET_USER_LOGOUT";

export const SET_USER_REGISTER_LOADING = "SET_USER_REGISTER_LOADING";
export const SET_USER_REGISTER_SUCCESS = "SET_USER_REGISTER_SUCCESS";
export const SET_USER_REGISTER_ERROR = "SET_USER_REGISTER_ERROR";

export const SET_USER_DETAILS_LOADING = "SET_USER_DETAILS_LOADING";
export const SET_USER_DETAILS_SUCCESS = "SET_USER_DETAILS_SUCCESS";
export const SET_USER_DETAILS_ERROR = "SET_USER_DETAILS_ERROR";

export const SET_USER_UPDATE_LOADING = "SET_USER_UPDATE_LOADING";
export const SET_USER_UPDATE_SUCCESS = "SET_USER_UPDATE_SUCCESS";
export const SET_USER_UPDATE_ERROR = "SET_USER_UPDATE_ERROR";
