export const SET_USER_LOGIN_LOADING = "SET_USER_LOGIN_LOADING";
export const SET_USER_LOGIN_SUCCESS = "SET_USER_LOGIN_SUCCESS";
export const SET_USER_LOGIN_ERROR = "SET_USER_LOGIN_ERROR";
export const SET_USER_LOGOUT = "SET_USER_LOGOUT";
